set psl-master to version 1.42 used by bookworm

diff --git a/init b/init
--- a/init
+++ b/init
@@ -1,6 +1,8 @@
 #!/bin/sh
 
-echo "Loading, please wait..."
+# Default PATH differs between shells, and is not automatically exported
+# by klibc dash.  Make it consistent.
+export PATH=/sbin:/usr/sbin:/bin:/usr/bin
 
 [ -d /dev ] || mkdir -m 0755 /dev
 [ -d /root ] || mkdir -m 0700 /root
@@ -8,25 +10,39 @@ echo "Loading, please wait..."
 [ -d /proc ] || mkdir /proc
 [ -d /tmp ] || mkdir /tmp
 mkdir -p /var/lock
-mount -t sysfs -o nodev,noexec,nosuid none /sys
-mount -t proc -o nodev,noexec,nosuid none /proc
+mount -t sysfs -o nodev,noexec,nosuid sysfs /sys
+mount -t proc -o nodev,noexec,nosuid proc /proc
+
+# shellcheck disable=SC2013
+for x in $(cat /proc/cmdline); do
+	case $x in
+	initramfs.clear)
+		clear
+		;;
+	quiet)
+		quiet=y
+		;;
+	esac
+done
+
+if [ "$quiet" != "y" ]; then
+	quiet=n
+	echo "Loading, please wait..."
+fi
+export quiet
 
 # Note that this only becomes /dev on the real filesystem if udev's scripts
 # are used; which they will be, but it's worth pointing out
-tmpfs_size="10M"
-if [ -e /etc/udev/udev.conf ]; then
-	. /etc/udev/udev.conf
-fi
-if ! mount -t devtmpfs -o mode=0755 none /dev; then
-	echo "W: devtmpfs not available, falling back to tmpfs for /dev"
-	mount -t tmpfs -o size=$tmpfs_size,mode=0755 udev /dev
-	[ -e /dev/console ] || mknod -m 0600 /dev/console c 5 1
-	[ -e /dev/null ] || mknod /dev/null c 1 3
-fi
+mount -t devtmpfs -o nosuid,mode=0755 udev /dev
+
+# Prepare the /dev directory
+[ ! -h /dev/fd ] && ln -s /proc/self/fd /dev/fd
+[ ! -h /dev/stdin ] && ln -s /proc/self/fd/0 /dev/stdin
+[ ! -h /dev/stdout ] && ln -s /proc/self/fd/1 /dev/stdout
+[ ! -h /dev/stderr ] && ln -s /proc/self/fd/2 /dev/stderr
+
 mkdir /dev/pts
-mount -t devpts -o noexec,nosuid,gid=5,mode=0620 none /dev/pts || true
-> /dev/.initramfs-tools
-mkdir /dev/.initramfs
+mount -t devpts -o noexec,nosuid,gid=5,mode=0620 devpts /dev/pts || true
 
 # Export the dpkg architecture
 export DPKG_ARCH=
@@ -41,12 +57,12 @@ export ROOTDELAY=
 export ROOTFLAGS=
 export ROOTFSTYPE=
 export IP=
+export DEVICE=
 export BOOT=
 export BOOTIF=
 export UBIMTD=
 export break=
 export init=/sbin/init
-export quiet=n
 export readonly=y
 export rootmnt=/root
 export debug=
@@ -54,15 +70,22 @@ export panic=
 export blacklist=
 export resume=
 export resume_offset=
+export noresume=
+export drop_caps=
+export fastboot=n
+export forcefsck=n
+export fsckfix=
+
 
 # Bring in the main config
 . /conf/initramfs.conf
 for conf in conf/conf.d/*; do
-	[ -f ${conf} ] && . ${conf}
+	[ -f "${conf}" ] && . "${conf}"
 done
 . /scripts/functions
 
 # Parse command line options
+# shellcheck disable=SC2013
 for x in $(cat /proc/cmdline); do
 	case $x in
 	init=*)
@@ -70,40 +93,9 @@ for x in $(cat /proc/cmdline); do
 		;;
 	root=*)
 		ROOT=${x#root=}
-		case $ROOT in
-		LABEL=*)
-			ROOT="${ROOT#LABEL=}"
-
-			# support any / in LABEL= path (escape to \x2f)
-			case "${ROOT}" in
-			*/*)
-			if command -v sed >/dev/null 2>&1; then
-				ROOT="$(echo ${ROOT} | sed 's,/,\\x2f,g')"
-			else
-				if [ "${ROOT}" != "${ROOT#/}" ]; then
-					ROOT="\x2f${ROOT#/}"
-				fi
-				if [ "${ROOT}" != "${ROOT%/}" ]; then
-					ROOT="${ROOT%/}\x2f"
-				fi
-				IFS='/'
-				newroot=
-				for s in $ROOT; do
-					newroot="${newroot:+${newroot}\\x2f}${s}"
-				done
-				unset IFS
-				ROOT="${newroot}"
-			fi
-			esac
-			ROOT="/dev/disk/by-label/${ROOT}"
-			;;
-		UUID=*)
-			ROOT="/dev/disk/by-uuid/${ROOT#UUID=}"
-			;;
-		/dev/nfs)
-			[ -z "${BOOT}" ] && BOOT=nfs
-			;;
-		esac
+		if [ -z "${BOOT}" ] && [ "$ROOT" = "/dev/nfs" ]; then
+			BOOT=nfs
+		fi
 		;;
 	rootflags=*)
 		ROOTFLAGS="-o ${x#rootflags=}"
@@ -120,7 +112,11 @@ for x in $(cat /proc/cmdline); do
 		esac
 		;;
 	nfsroot=*)
+		# shellcheck disable=SC2034
 		NFSROOT="${x#nfsroot=}"
+		;;
+	initramfs.runsize=*)
+		RUNSIZE="${x#initramfs.runsize=}"
 		;;
 	ip=*)
 		IP="${x#ip=}"
@@ -140,16 +136,11 @@ for x in $(cat /proc/cmdline); do
 	noresume)
 		noresume=y
 		;;
+	drop_capabilities=*)
+		drop_caps="-d ${x#drop_capabilities=}"
+		;;
 	panic=*)
 		panic="${x#panic=}"
-		case ${panic} in
-		*[![:digit:].]*)
-			panic=
-			;;
-		esac
-		;;
-	quiet)
-		quiet=y
 		;;
 	ro)
 		readonly=y
@@ -160,7 +151,11 @@ for x in $(cat /proc/cmdline); do
 	debug)
 		debug=y
 		quiet=n
-		exec >/dev/.initramfs/initramfs.debug 2>&1
+		if [ -n "${netconsole}" ]; then
+			log_output=/dev/kmsg
+		else
+			log_output=/run/initramfs/initramfs.debug
+		fi
 		set -x
 		;;
 	debug=*)
@@ -179,31 +174,63 @@ for x in $(cat /proc/cmdline); do
 		;;
 	netconsole=*)
 		netconsole=${x#netconsole=}
+		[ "$debug" = "y" ] && log_output=/dev/kmsg
 		;;
 	BOOTIF=*)
 		BOOTIF=${x#BOOTIF=}
 		;;
+	fastboot|fsck.mode=skip)
+		fastboot=y
+		;;
+	forcefsck|fsck.mode=force)
+		forcefsck=y
+		;;
+	fsckfix|fsck.repair=yes)
+		fsckfix=y
+		;;
+	fsck.repair=no)
+		fsckfix=n
+		;;
 	esac
 done
 
-if [ -n "${noresume}" ]; then
-	export noresume
-	unset resume
+# Default to BOOT=local if no boot script defined.
+if [ -z "${BOOT}" ]; then
+	BOOT=local
+fi
+
+if [ -n "${noresume}" ] || [ "$RESUME" = none ]; then
+	noresume=y
 else
 	resume=${RESUME:-}
 fi
 
-[ -n "${netconsole}" ] && modprobe netconsole netconsole="${netconsole}"
+mount -t tmpfs -o "nodev,noexec,nosuid,size=${RUNSIZE:-10%},mode=0755" tmpfs /run
+mkdir -m 0700 /run/initramfs
+
+if [ -n "$log_output" ]; then
+	exec >"$log_output" 2>&1
+	unset log_output
+fi
 
 maybe_break top
 
-# Don't do log messages here to avoid confusing usplash
+# Don't do log messages here to avoid confusing graphical boots
 run_scripts /scripts/init-top
 
 maybe_break modules
 [ "$quiet" != "y" ] && log_begin_msg "Loading essential drivers"
+[ -n "${netconsole}" ] && /sbin/modprobe netconsole netconsole="${netconsole}"
 load_modules
 [ "$quiet" != "y" ] && log_end_msg
+
+starttime="$(_uptime)"
+starttime=$((starttime + 1)) # round up
+export starttime
+
+if [ "$ROOTDELAY" ]; then
+	sleep "$ROOTDELAY"
+fi
 
 maybe_break premount
 [ "$quiet" != "y" ] && log_begin_msg "Running /scripts/init-premount"
@@ -212,73 +239,63 @@ run_scripts /scripts/init-premount
 
 maybe_break mount
 log_begin_msg "Mounting root file system"
-. /scripts/${BOOT}
-parse_numeric ${ROOT}
+# Always load local and nfs (since these might be needed for /etc or
+# /usr, irrespective of the boot script used to mount the rootfs).
+. /scripts/local
+. /scripts/nfs
+. "/scripts/${BOOT}"
+parse_numeric "${ROOT}"
 maybe_break mountroot
+mount_top
+mount_premount
 mountroot
 log_end_msg
 
+if read_fstab_entry /usr; then
+	log_begin_msg "Mounting /usr file system"
+	mountfs /usr
+	log_end_msg
+fi
+
+# Mount cleanup
+mount_bottom
+nfs_bottom
+local_bottom
+
 maybe_break bottom
 [ "$quiet" != "y" ] && log_begin_msg "Running /scripts/init-bottom"
+# We expect udev's init-bottom script to move /dev to ${rootmnt}/dev
 run_scripts /scripts/init-bottom
 [ "$quiet" != "y" ] && log_end_msg
 
-# Move virtual filesystems over to the real filesystem
-mount -n -o move -t sysfs /sys ${rootmnt}/sys
-mount -n -o move -t proc /proc ${rootmnt}/proc
+# Move /run to the root
+mount -n -o move /run ${rootmnt}/run
 
 validate_init() {
-	checktarget="${1}"
-
-	# Work around absolute symlinks
-	if [ -d "${rootmnt}" ] && [ -h "${rootmnt}${checktarget}" ]; then
-		case $(readlink "${rootmnt}${checktarget}") in /*)
-			checktarget="$(chroot ${rootmnt} readlink ${checktarget})"
-			;;
-		esac
-	fi
-
-	# Make sure the specified init can be executed
-	if [ ! -x "${rootmnt}${checktarget}" ]; then
-		return 1
-	fi
-
-	# Upstart uses /etc/init as configuration directory :-/
-	if [ -d "${rootmnt}${checktarget}" ]; then
-		return 1
-	fi
+	run-init -n "${rootmnt}" "${1}"
 }
 
-# Check init bootarg
-if [ -n "${init}" ]; then
-	if ! validate_init "$init"; then
-		echo "Target filesystem doesn't have requested ${init}."
-		init=
-	fi
+# Check init is really there
+if ! validate_init "$init"; then
+	echo "Target filesystem doesn't have requested ${init}."
+	init=
+	for inittest in /sbin/init /etc/init /bin/init /bin/sh; do
+		if validate_init "${inittest}"; then
+			init="$inittest"
+			break
+		fi
+	done
 fi
 
-# Common case: /sbin/init is present
-if [ ! -x "${rootmnt}/sbin/init" ]; then
-	# ... if it's not available search for valid init
-	if [ -z "${init}" ] ; then
-		for inittest in /sbin/init /etc/init /bin/init /bin/sh; do
-			if validate_init "${inittest}"; then
-				init="$inittest"
-				break
-			fi
-		done
-	fi
-
-	# No init on rootmount
-	if ! validate_init "${init}" ; then
-		panic "No init found. Try passing init= bootarg."
-	fi
+# No init on rootmount
+if ! validate_init "${init}" ; then
+	panic "No init found. Try passing init= bootarg."
 fi
 
 maybe_break init
 
 # don't leak too much of env - some init(8) don't clear it
-# (keep init, rootmnt)
+# (keep init, rootmnt, drop_caps)
 unset debug
 unset MODPROBE_OPTIONS
 unset DPKG_ARCH
@@ -289,6 +306,7 @@ unset ROOT
 unset IP
 unset BOOT
 unset BOOTIF
+unset DEVICE
 unset UBIMTD
 unset blacklist
 unset break
@@ -298,7 +316,18 @@ unset quiet
 unset readonly
 unset resume
 unset resume_offset
+unset noresume
+unset fastboot
+unset forcefsck
+unset fsckfix
+unset starttime
+
+# Move virtual filesystems over to the real filesystem
+mount -n -o move /sys ${rootmnt}/sys
+mount -n -o move /proc ${rootmnt}/proc
 
 # Chain to real filesystem
-exec run-init ${rootmnt} ${init} "$@" <${rootmnt}/dev/console >${rootmnt}/dev/console
-panic "Could not execute run-init."
+# shellcheck disable=SC2086,SC2094
+exec run-init ${drop_caps} "${rootmnt}" "${init}" "$@" <"${rootmnt}/dev/console" >"${rootmnt}/dev/console" 2>&1
+echo "Something went badly wrong in the initramfs."
+panic "Please file a bug on initramfs-tools."
diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -2,259 +2,133 @@
 
 _log_msg()
 {
-	if [ "$quiet" = "y" ]; then return; fi
+	if [ "${quiet?}" = "y" ]; then return; fi
+	# shellcheck disable=SC2059
 	printf "$@"
+	return 0 # Prevents error carry over in case of unavailable console
 }
 
 log_success_msg()
 {
-	_log_msg "Success: $@\n"
+	_log_msg "Success: %s\\n" "$*"
 }
 
 log_failure_msg()
 {
-	_log_msg "Failure: $@\n"
+	_log_msg "Failure: %s\\n" "$*"
 }
 
 log_warning_msg()
 {
-	_log_msg "Warning: $@\n"
+	_log_msg "Warning: %s\\n" "$*"
 }
 
 log_begin_msg()
 {
-	if [ -x /sbin/usplash_write ]; then
-		/sbin/usplash_write "TEXT $@"
-	fi
-	_log_msg "Begin: $@ ... "
+	_log_msg "Begin: %s ... " "$*"
 }
 
 log_end_msg()
 {
-	if [ -x /sbin/usplash_write ]; then
-		/sbin/usplash_write "SUCCESS ok"
-	fi
-	_log_msg "done.\n"
+	_log_msg "done.\\n"
 }
 
 panic()
 {
-	if [ -x /sbin/usplash_write ]; then
-		/sbin/usplash_write "QUIT"
-	fi
+	local console rest IFS
 
 	if command -v chvt >/dev/null 2>&1; then
 		chvt 1
 	fi
 
-	# Disallow console access
-	if [ -n "${panic}" ]; then
-		sleep ${panic}
-		reboot
-	fi
-	modprobe i8042
-	modprobe atkbd
 	echo "$@"
-	REASON="$@" PS1='(initramfs) ' /bin/sh -i </dev/console >/dev/console 2>&1
+
+	# The panic= parameter implies we should disallow console access
+	if [ -n "${panic?}" ]; then
+		delay=
+		case "${panic?}" in
+		-*[![:digit:].]*)	# invalid: wait forever
+			;;
+		-*)			# timeout < 0: reboot immediately
+			delay=0
+			;;
+		0 | *[![:digit:].]*)	# timeout = 0 or invalid: wait forever
+			;;
+		*)			# timeout > 0: seconds before rebooting
+			delay="${panic}"
+			;;
+		esac
+		if [ -n "${delay}" ]; then
+			echo "Rebooting automatically due to panic= boot argument"
+			sleep "${delay}"
+			reboot -f
+		else
+			echo "Halting automatically due to panic= boot argument"
+			halt -f
+		fi
+		exit  # in case reboot fails, force kernel panic
+	fi
+
+	run_scripts /scripts/panic
+
+	# Try to use setsid, which will enable job control in the shell
+	# and paging in more
+	if command -v setsid >/dev/null 2>&1; then
+		unset IFS
+		read -r console rest </proc/consoles
+		if [ "${console}" = "tty0" ]; then
+			# Need to choose a specific VT
+			console="tty1"
+		fi
+		# We don't have 'setsid -c' so we need to setsid, open
+		# the tty, and finally exec an interactive shell
+		REASON="$*" PS1='(initramfs) ' setsid sh -c "exec sh -i <>/dev/${console} 1>&0 2>&1"
+	else
+		REASON="$*" PS1='(initramfs) ' sh -i </dev/console >/dev/console 2>&1
+	fi
 }
 
 maybe_break()
 {
-	if [ "${break:-}" = "$1" ]; then
-		panic "Spawning shell within the initramfs"
-	fi
-}
-
-render()
-{
-	eval "echo -n \${$@}"
-}
-
-set_initlist()
-{
-	unset initlist
-	for si_x in ${initdir}/*; do
-		# skip empty dirs without warning
-		[ "${si_x}" = "${initdir}/*" ] && return
-
-		# only allow variable name chars
-		case ${si_x#${initdir}/} in
-		*[![:alnum:]\._-]*)
-			[ "${verbose}" = "y" ] \
-			&& echo "$si_x ignored: not alphanumeric or '_' file"
-			continue
-			;;
-		esac
-
-		# skip non executable scripts
-		if [ ! -x ${si_x} ]; then
-			[ "${verbose}" = "y" ] \
-			&& echo "$si_x ignored: not executable"
-			continue
-		fi
-
-		# skip directories
-		if [ -d ${si_x} ]; then
-			[ "${verbose}" = "y" ] \
-			&& echo "$si_x ignored: a directory"
-			continue
-		fi
-
-		# skip bad syntax
-		if ! sh -n ${si_x} ; then
-			[ "${verbose}" = "y" ] \
-			&& echo "$si_x ignored: bad syntax"
-			continue
-		fi
-
-		initlist="${initlist:-} ${si_x#${initdir}/}"
-	done
-}
-
-reduce_satisfied()
-{
-	deplist="$(render array_${1})"
-	unset tmpdeplist
-	for rs_y in ${deplist}; do
-		# only allow variable name chars
-		case ${rs_y} in
-		*[![:alnum:]\._-]*)
-			continue
-			;;
-		esac
-		# skip non executable scripts
-		[ ! -x ${initdir}/${rs_y} ] && continue
-		# skip directories
-		[ -d ${initdir}/${rs_y} ] && continue
-		# skip bad syntax
-		sh -n ${initdir}/${rs_y} || continue
-
-		tmpdeplist="${tmpdeplist} ${rs_y}"
-	done
-	deplist=${tmpdeplist}
-	for rs_x in ${runlist}; do
-		pop_list_item ${rs_x} ${deplist}
-		deplist=${tmppop}
-	done
-	eval array_${1}=\"${deplist}\"
-}
-
-get_prereqs()
-{
-	set_initlist
-	for gp_x in ${initlist}; do
-		tmp=$(${initdir}/${gp_x} prereqs)
-		eval array_${gp_x}=\"${tmp}\"
-	done
-}
-
-count_unsatisfied()
-{
-	set -- ${@}
-	return ${#}
-}
-
-# Removes $1 from initlist
-pop_list_item()
-{
-	item=${1}
-	shift
-	set -- ${@}
-	unset tmppop
-	# Iterate
-	for pop in ${@}; do
-		if [ ${pop} = ${item} ]; then
-			continue
-		fi
-		tmppop="${tmppop} ${pop}"
-	done
-
-}
-
-# This function generates the runlist, so we clear it first.
-reduce_prereqs()
-{
-	unset runlist
-	set -- ${initlist}
-	i=$#
-	# Loop until there's no more in the queue to loop through
-	while [ ${i} -ne 0 ]; do
-		oldi=${i}
-		for rp_x in ${initlist}; do
-			reduce_satisfied ${rp_x}
-			count_unsatisfied $(render array_${rp_x})
-			cnt=${?}
-			if [ ${cnt} -eq 0 ]; then
-				runlist="${runlist} ${rp_x}"
-				pop_list_item ${rp_x} ${initlist}
-				initlist=${tmppop}
-				i=$((${i} - 1))
+	case ",${break?}," in
+	*,$1,*)
+		if [ "$1" = "top" ]; then
+			# udev is not yet running, so load keyboard drivers
+			if [ "${quiet}" = "y" ]; then
+				opts="-q"
+			else
+				opts="-v"
 			fi
-		done
-		if [ ${i} -eq ${oldi} ]; then
-			panic "PANIC: Circular dependancy.  Exiting."
+			/sbin/modprobe ${opts} -a i8042 atkbd ehci-pci ehci-orion \
+				 ehci-hcd ohci-hcd ohci-pci uhci-hcd usbhid xhci \
+				 xhci-pci xhci-hcd
+			sleep 2
+			for modalias in /sys/bus/hid/devices/*/modalias; do
+				if [ -f "${modalias}" ]; then
+					/sbin/modprobe ${opts} -b "$(cat "${modalias}")"
+				fi
+			done
 		fi
-	done
+		panic "Spawning shell within the initramfs"
+		;;
+	esac
 }
 
-get_prereq_pairs()
-{
-	set_initlist
-	for gp_x in ${initlist:-}; do
-		echo ${gp_x} ${gp_x}
-		prereqs=$(${initdir}/${gp_x} prereqs)
-		for prereq in ${prereqs}; do
-			echo ${prereq} ${gp_x}
-		done
-	done
-}
-
-call_scripts()
-{
-	set -e
-	for cs_x in ${runlist}; do
-		[ -f ${initdir}/${cs_x} ] || continue
-		# mkinitramfs verbose output
-		if [ "${verbose}" = "y" ]; then
-			echo "Calling hook ${cs_x}"
-		fi
-		${initdir}/${cs_x} && ec=$? || ec=$?
-		# allow hooks to abort build:
-		if [ "$ec" -ne 0 ]; then
-			echo "E: ${initdir}/${cs_x} failed with return $ec."
-			# only errexit on mkinitramfs
-			[ -n "${version}" ] && exit $ec
-		fi
-		# allow boot scripts to modify exported boot parameters
-		if [ -e /conf/param.conf ]; then
-			. /conf/param.conf
-		fi
-	done
-	set +e
-}
-
+# For boot time only; this is overridden at build time in hook-functions
 run_scripts()
 {
 	initdir=${1}
-	[ ! -d ${initdir} ] && return
+	[ ! -d "${initdir}" ] && return
 
-	if [ -f ${initdir}/ORDER ]; then
-		. ${initdir}/ORDER
-	elif command -v tsort >/dev/null 2>&1; then
-		runlist=$(get_prereq_pairs | tsort)
-		call_scripts ${2:-}
-	else
-		get_prereqs
-		reduce_prereqs
-		call_scripts
-	fi
+	shift
+	. "${initdir}/ORDER"
 }
 
 # Load custom modules first
 load_modules()
 {
 	if [ -e /conf/modules ]; then
-		cat /conf/modules | while read m; do
+		while read -r m; do
 			# Skip empty lines
 			if [ -z "$m" ];  then
 				continue
@@ -264,36 +138,59 @@ load_modules()
 			if [ "$com" = "#" ]; then
 				continue
 			fi
-			modprobe $m
-		done
+			# shellcheck disable=SC2086
+			/sbin/modprobe $m
+		done < /conf/modules
 	fi
+}
+
+_uptime() {
+	local uptime
+	uptime="$(cat /proc/uptime)"
+	uptime="${uptime%%[. ]*}"
+	echo "$uptime"
+}
+
+time_elapsed() {
+	# shellcheck disable=SC2154
+	if [ -z "$starttime" ]; then
+		log_failure_msg "time_elapsed() called before \$starttime initialized"
+		echo 0
+	fi
+	local delta
+	delta="$(_uptime)"
+	delta=$((delta - starttime))
+	echo "$delta"
 }
 
 # lilo compatibility
 parse_numeric() {
 	case $1 in
-	"")
-		return
-		;;
-	/*)
-		return
-		;;
-	[0-9]*:[0-9]*)
+	*:*)
+		# Does it match /[0-9]*:[0-9]*/?
 		minor=${1#*:}
 		major=${1%:*}
+		case $major$minor in
+		*[!0-9]*)
+			# No.
+			return
+			;;
+		esac
 		;;
-	[A-Fa-f0-9]*)
-		value=$(( 0x${1} ))
-		minor=$(( ${value} % 256 ))
-		major=$(( ${value} / 256 ))
+	"" | *[!A-Fa-f0-9]*)
+		# "", "/*", etc.
+		return
 		;;
 	*)
-		return
+		# [A-Fa-f0-9]*
+		value=$(( 0x${1} ))
+		minor=$(( (value & 0xff) | (value >> 12) & 0xfff00 ))
+		major=$(( (value >> 8) & 0xfff ))
 		;;
 	esac
 
-	mknod -m 600 /dev/root b ${major} ${minor}
-	ROOT=/dev/root
+	# shellcheck disable=SC2034
+	ROOT="/dev/block/${major}:${minor}"
 }
 
 # Parameter: device node to check
@@ -301,34 +198,101 @@ parse_numeric() {
 # Return value: indicates if an fs could be recognized
 get_fstype ()
 {
-	local FS FSTYPE FSSIZE RET
+	local FS FSTYPE
 	FS="${1}"
 
 	# blkid has a more complete list of file systems,
 	# but fstype is more robust
-	eval $(fstype "${FS}" 2> /dev/null)
-	if [ "$FSTYPE" = "unknown" ] &&  command -v blkid >/dev/null 2>&1 ; then
-		FSTYPE=$(blkid -o value -s TYPE "${FS}")
-	elif [ "$FSTYPE" = "unknown" ] && [ -x /lib/udev/vol_id ]; then
-		FSTYPE=$(/lib/udev/vol_id -t "${FS}" 2> /dev/null)
+	FSTYPE="unknown"
+	eval "$(fstype "${FS}" 2> /dev/null)"
+	if [ "$FSTYPE" = "unknown" ]; then
+		FSTYPE=$(blkid -o value -s TYPE "${FS}") || return
 	fi
-	RET=$?
-
-	if [ -z "${FSTYPE}" ]; then
-		FSTYPE="unknown"
-	fi
-
 	echo "${FSTYPE}"
-	return ${RET}
+	return 0
+}
+
+_set_netdev_from_ip_param()
+{
+	# If the ip= parameter is present and specifies a device, use
+	# that in preference to any device name we already have
+	local IFS=:
+	set -f
+	# shellcheck disable=SC2086
+	set -- ${IP}
+	set +f
+	if [ -n "$6" ]; then
+		DEVICE="$6"
+		return 0
+	fi
+	return 1
+}
+
+_set_netdev_from_hw_address()
+{
+	local want_address="$1"
+	local device
+	for device in /sys/class/net/*; do
+		if [ -f "$device/address" ] &&
+		   [ "$(cat "$device/address")" = "$want_address" ]; then
+			DEVICE="${device##*/}"
+			return 0
+		fi
+	done
+	return 1
+}
+
+_usable_netdev_exists()
+{
+	# Look for a device with IFF_LOOPBACK clear and (IFF_BROADCAST
+	# or IFF_POINTTOPOINT) set.  This is the same test the kernel
+	# and ipconfig apply to find a device.
+	local device
+	local flags
+	for device in /sys/class/net/*; do
+		if [ -f "${device}/flags" ]; then
+			flags="$(cat "${device}/flags")"
+			if [ "$((flags & 8))" -eq 0 ] &&
+			   [ "$((flags & 0x12))" -ne 0 ]; then
+				return 0
+			fi
+		fi
+	done
+	return 1
+}
+
+_update_ip_param()
+{
+	# If the ip= parameter is present, and is a colon-separated list,
+	# but does not specify a device, substitute in the device name
+	# we have
+	local IFS=:
+	set -f
+	# shellcheck disable=SC2086
+	set -- ${IP}
+	set +f
+	if [ -z "$6" ] && [ $# -ge 2 ] && [ -n "${DEVICE}" ]; then
+		IP="$1:$2:$3:$4:$5:${DEVICE}"
+		shift 6 || shift $#
+		IP="${IP}:$*"
+	fi
 }
 
 configure_networking()
 {
-	if [ -n "${BOOTIF}" ]; then
+	local netdev_desc
+
+	# The order of precedence here is:
+	# 1. Device specified by ip= kernel parameter
+	# 2. Device matching MAC specified by BOOTIF= kernel parameter
+	# 3. Build-time DEVICE variable
+	# In case 2 we only discover the device name while waiting
+	# for a device.
+	if _set_netdev_from_ip_param; then
+		netdev_desc="${DEVICE}"
+	elif [ -n "${BOOTIF}" ]; then
 		# pxelinux sets BOOTIF to a value based on the mac address of the
-		# network card used to PXE boot, so use this value for DEVICE rather
-		# than a hard-coded device name from initramfs.conf. this facilitates
-		# network booting when machines may have multiple network cards.
+		# network card used to PXE boot
 		# pxelinux sets BOOTIF to 01-$mac_address
 
 		# strip off the leading "01-", which isn't part of the mac
@@ -347,24 +311,41 @@ configure_networking()
 		done
 		unset IFS
 
-		# look for devices with matching mac address, and set DEVICE to
-		# appropriate value if match is found.
-		for device in /sys/class/net/* ; do
-			if [ -f "$device/address" ]; then
-				current_mac=$(cat "$device/address")
-				if [ "$bootif_mac" = "$current_mac" ]; then
-					DEVICE=${device##*/}
-					break
-				fi
-			fi
-		done
+		_set_netdev_from_hw_address "${bootif_mac}"
+		netdev_desc="device with address ${bootif_mac}"
+	elif [ -n "${DEVICE}" ]; then
+		netdev_desc="${DEVICE}"
+	else
+		netdev_desc="any network device"
 	fi
 
 	# networking already configured thus bail out
-	[ -n "${DEVICE}" ] && [ -e /tmp/net-"${DEVICE}".conf ] && return 0
+	[ -n "${DEVICE}" ] && [ -e /run/net-"${DEVICE}".conf ] && return 0
+
+	local netdevwait=180
+	log_begin_msg "Waiting up to ${netdevwait} secs for ${netdev_desc} to become available"
+	while true; do
+		if [ "$(time_elapsed)" -ge "$netdevwait" ]; then
+			log_failure_msg "Network device did not appear in time"
+			break
+		fi
+		if [ -n "${DEVICE}" ]; then
+			[ -e "/sys/class/net/${DEVICE}" ] && break
+		elif [ -n "${bootif_mac}" ]; then
+			_set_netdev_from_hw_address "${bootif_mac}" && break
+		else
+			_usable_netdev_exists && break
+		fi
+		sleep 1
+	done
+	log_end_msg
+
+	_update_ip_param
+
+	wait_for_udev 10
 
 	# support ip options see linux sources
-	# Documentation/filesystems/nfsroot.txt
+	# Documentation/filesystems/nfs/nfsroot.txt
 	# Documentation/frv/booting.txt
 
 	for ROUNDTTT in 2 3 4 6 9 16 25 36 64 100; do
@@ -372,7 +353,7 @@ configure_networking()
 		# The NIC is to be configured if this file does not exist.
 		# Ip-Config tries to create this file and when it succeds
 		# creating the file, ipconfig is not run again.
-		for x in /tmp/net-"${DEVICE}".conf /tmp/net-*.conf ; do
+		for x in /run/net-"${DEVICE}".conf /run/net-*.conf ; do
 			[ -e "$x" ] && break 2
 		done
 
@@ -385,22 +366,10 @@ configure_networking()
 			ipconfig -t ${ROUNDTTT} "${DEVICE}"
 			;;
 		dhcp|bootp|rarp|both)
-			ipconfig -t ${ROUNDTTT} -c ${IP} -d "${DEVICE}"
+			ipconfig -t ${ROUNDTTT} -c "${IP}" -d "${DEVICE}"
 			;;
 		*)
-			ipconfig -t ${ROUNDTTT} -d $IP
-
-			# grab device entry from ip option
-			NEW_DEVICE=${IP#*:*:*:*:*:*}
-			if [ "${NEW_DEVICE}" != "${IP}" ]; then
-				NEW_DEVICE=${NEW_DEVICE%:*}
-			else
-				# wrong parse, possibly only a partial string
-				NEW_DEVICE=
-			fi
-			if [ -n "${NEW_DEVICE}" ]; then
-				DEVICE="${NEW_DEVICE}"
-			fi
+			ipconfig -t ${ROUNDTTT} -d "$IP"
 			;;
 		esac
 	done
@@ -408,11 +377,11 @@ configure_networking()
 	# source ipconfig output
 	if [ -n "${DEVICE}" ]; then
 		# source specific bootdevice
-		. /tmp/net-${DEVICE}.conf
+		. "/run/net-${DEVICE}.conf"
 	else
 		# source any interface...
 		# ipconfig should have quit after first response
-		. /tmp/net-*.conf
+		. /run/net-*.conf
 	fi
 }
 
@@ -421,4 +390,192 @@ wait_for_udev()
 {
 	command -v udevadm >/dev/null 2>&1 || return 0
 	udevadm settle ${1:+--timeout=$1}
+}
+
+# Find a specific fstab entry
+# $1=mountpoint
+# $2=fstype (optional)
+# returns 0 on success, 1 on failure (not found or no fstab)
+read_fstab_entry() {
+	# Not found by default.
+	found=1
+
+	for file in ${rootmnt?}/etc/fstab; do
+		if [ -f "$file" ]; then
+			# shellcheck disable=SC2034
+			while read -r MNT_FSNAME MNT_DIR MNT_TYPE MNT_OPTS MNT_FREQ MNT_PASS MNT_JUNK; do
+				case "$MNT_FSNAME" in
+				  ""|\#*)
+					continue;
+					;;
+				esac
+				if [ "$MNT_DIR" = "$1" ]; then
+					if [ -n "$2" ]; then
+						[ "$MNT_TYPE" = "$2" ] || continue;
+					fi
+					found=0
+					break 2
+				fi
+			done < "$file"
+		fi
+	done
+
+	return $found
+}
+
+# Resolve device node from a name.  This expands any LABEL or UUID.
+# $1=name
+# Resolved name is echoed.
+resolve_device() {
+	DEV="$1"
+
+	case "$DEV" in
+	LABEL=* | UUID=* | PARTLABEL=* | PARTUUID=*)
+		DEV="$(blkid -l -t "$DEV" -o device)" || return 1
+		;;
+	esac
+	[ -e "$DEV" ] && echo "$DEV"
+}
+
+# Check a file system.
+# $1=device
+# $2=mountpoint (for diagnostics only)
+# $3=type (may be "auto")
+_checkfs_once()
+{
+	DEV="$1"
+	NAME="$2"
+	TYPE="$3"
+	if [ "$NAME" = "/" ] ; then
+		NAME="root"
+	fi
+	FSCK_LOGFILE=/run/initramfs/fsck.log
+	FSCK_STAMPFILE=/run/initramfs/fsck-${NAME#/}
+
+	if [ "${TYPE}" = "auto" ]; then
+		TYPE="$(get_fstype "${DEV}")"
+	fi
+
+	FSCKCODE=0
+	if [ -z "${TYPE}" ]; then
+		log_warning_msg "Type of $NAME file system is unknown, so skipping check."
+		return
+	fi
+	if ! command -v fsck >/dev/null 2>&1; then
+		log_warning_msg "fsck not present, so skipping $NAME file system"
+		return
+	fi
+	if [ "${fastboot?}" = "y" ] ; then
+		log_warning_msg "Fast boot enabled, so skipping $NAME file system check."
+		return
+	fi
+
+	if [ "${forcefsck?}" = "y" ]
+	then
+		force="-f"
+	else
+		force=""
+	fi
+
+	if [ "${fsckfix?}" = "y" ]
+	then
+		fix="-y"
+	elif [ "${fsckfix?}" = "n" ]
+	then
+		fix="-n"
+	else
+		fix="-a"
+	fi
+
+	spinner=""
+	if [ -z "${debug?}" ]; then
+		spinner="-C"
+	fi
+
+	if [ "${quiet}" = n ]
+	then
+		log_begin_msg "Will now check $NAME file system"
+		# shellcheck disable=SC2086
+		logsave -a -s $FSCK_LOGFILE fsck $spinner $force $fix -V -t "$TYPE" "$DEV"
+		FSCKCODE=$?
+		log_end_msg
+	else
+		log_begin_msg "Checking $NAME file system"
+		# shellcheck disable=SC2086
+		logsave -a -s $FSCK_LOGFILE fsck $spinner $force $fix -T -t "$TYPE" "$DEV"
+		FSCKCODE=$?
+		log_end_msg
+	fi
+
+	# NOTE: "failure" is defined as exiting with a return code of
+	# 4, possibly or-ed with other flags. A return code of 1
+	# indicates that file system errors were corrected but that
+	# the boot may proceed.
+	#
+	if [ "$FSCKCODE" -eq 32 ]
+	then
+		log_warning_msg "File system check was interrupted by user"
+	elif [ $((FSCKCODE & 4)) -eq 4 ]
+	then
+		log_failure_msg "File system check of the $NAME filesystem failed"
+		return 1
+	elif [ "$FSCKCODE" -gt 1 ]
+	then
+		log_warning_msg "File system check failed but did not detect errors"
+		sleep 5
+	else
+		true >"$FSCK_STAMPFILE"
+	fi
+	return 0
+}
+
+checkfs()
+{
+	while ! _checkfs_once "$@"; do
+		panic "The $2 filesystem on $1 requires a manual fsck"
+	done
+}
+
+# Mount a file system.  We parse the information from the fstab.  This
+# should be overridden by any boot script which can mount arbitrary
+# filesystems such as /usr.  This default implementation delegates to
+# local or nfs based upon the filesystem type.
+# $1=mountpoint mount location
+mountfs()
+{
+	type=local
+	read_fstab_entry "$1"
+	if [ "${MNT_TYPE}" = "nfs" ] || [ "${MNT_TYPE}" = "nfs4" ]; then
+		type=nfs
+	fi
+
+	${type}_mount_fs "$1"
+}
+
+# Mount the root file system.  It should be overridden by all
+# boot scripts.
+mountroot()
+{
+	:
+}
+
+# Run /scripts/${boot}-top.  This should be overridden by all boot
+# scripts.
+mount_top()
+{
+	:
+}
+
+# Run /scripts/${boot}-premount.  This should be overridden by all boot
+# scripts.
+mount_premount()
+{
+	:
+}
+
+# Run /scripts/${boot}-bottom.  This should be overridden by all boot
+# scripts.
+mount_bottom()
+{
+	:
 }
diff --git a/update-initramfs b/update-initramfs
--- a/update-initramfs
+++ b/update-initramfs
@@ -1,10 +1,7 @@
 #!/bin/sh
 
-STATEDIR=/var/lib/initramfs-tools
 BOOTDIR=/boot
 CONF=/etc/initramfs-tools/update-initramfs.conf
-KPKGCONF=/etc/kernel-img.conf
-USETRIGGERS=true
 mode=""
 version=""
 update_initramfs=yes
@@ -14,12 +11,7 @@ set -e
 
 [ -r ${CONF} ] && . ${CONF}
 
-if	   $USETRIGGERS						\
-	&& [ x"${DPKG_MAINTSCRIPT_PACKAGE:-}" != x ]		\
-	&& [ $# = 1 ]	 					\
-	&& [ x"$1" = x-u ]					\
-	&& dpkg-trigger --check-supported 2>/dev/null
-then
+if [ -n "$DPKG_MAINTSCRIPT_PACKAGE" ] && [ $# = 1 ] && [ "$1" = -u ]; then
 	if dpkg-trigger --no-await update-initramfs; then
 		echo "update-initramfs: deferring update (trigger activated)"
 		exit 0
@@ -28,43 +20,36 @@ fi
 
 usage()
 {
-	if [ -n "${1:-}" ]; then
-		printf "${*}\n\n" >&2
-	fi
-	cat >&2 << EOF
-Usage: ${0} [OPTION]...
+	cat << EOF
+
+Usage: update-initramfs {-c|-d|-u} [-k version] [-v] [-b directory]
 
 Options:
- -k [version]	Specify kernel version or 'all'
+ -k version	Specify kernel version or 'all'
  -c		Create a new initramfs
  -u		Update an existing initramfs
  -d		Remove an existing initramfs
- -t		Take over a custom initramfs with this one
- -b		Set alternate boot directory
+ -b directory	Set alternate boot directory
  -v		Be verbose
- -h		This message
+
+See update-initramfs(8) for further details.
 
 EOF
-	exit 1
 }
 
-# chroot check
-chrooted()
+usage_error()
 {
-	# borrowed from udev's postinst
-	if [ "$(stat -c %d/%i /)" = "$(stat -Lc %d/%i /proc/1/root 2>/dev/null)" ]; then
-		# the devicenumber/inode pair of / is the same as that of
-		# /sbin/init's root, so we're *not* in a chroot and hence
-		# return false.
-		return 1
+	if [ -n "${1:-}" ]; then
+		printf "%s\\n\\n" "${*}" >&2
 	fi
-return 0
+	usage >&2
+	exit 2
 }
 
 mild_panic()
 {
 	if [ -n "${1:-}" ]; then
-		printf "${*}\n" >&2
+		printf "%s\\n" "${*}" >&2
 	fi
 	exit 0
 }
@@ -72,7 +57,7 @@ mild_panic()
 panic()
 {
 	if [ -n "${1:-}" ]; then
-		printf "${*}\n" >&2
+		printf "%s\\n" "${*}" >&2
 	fi
 	exit 1
 }
@@ -80,14 +65,8 @@ panic()
 verbose()
 {
 	if [ "${verbose}" = 1 ]; then
-		printf "${*}\n"
+		printf "%s\\n" "${*}"
 	fi
-}
-
-version_exists()
-{
-	[ -e "${STATEDIR}/${1}" ] && [ -e "${initramfs}" ]
-	return $?
 }
 
 set_initramfs()
@@ -123,7 +102,7 @@ backup_booted_initramfs()
 
 	# no backup yet
 	if [ ! -r "${initramfs}.bak" ]; then
-		mv -f ${initramfs_bak} "${initramfs}.bak"
+		mv -f "${initramfs_bak}" "${initramfs}.bak"
 		verbose "Backup ${initramfs}.bak"
 		return 0
 	fi
@@ -132,7 +111,7 @@ backup_booted_initramfs()
 	boot_initramfs=
 	uptime_days=$(awk '{printf "%d", $1 / 3600 / 24}' /proc/uptime)
 	if [ -n "$uptime_days" ]; then
-		boot_initramfs=$(find "${initramfs}.bak" -mtime +${uptime_days})
+		boot_initramfs=$(find "${initramfs}.bak" -mtime "+${uptime_days}")
 	fi
 	if [ -n "${boot_initramfs}" ]; then
 		mv -f "${initramfs_bak}" "${initramfs}.bak"
@@ -140,7 +119,7 @@ backup_booted_initramfs()
 		return 0
 	fi
 	verbose "Removing current backup ${initramfs_bak}"
-	rm -f ${initramfs_bak}
+	rm -f "${initramfs_bak}"
 }
 
 # nuke generated copy
@@ -159,32 +138,18 @@ generate_initramfs()
 	if [ "${verbose}" = 1 ]; then
 		OPTS="-v ${OPTS}"
 	fi
+	# shellcheck disable=SC2086
 	if mkinitramfs ${OPTS} "${initramfs}.new" "${version}"; then
 		mv -f "${initramfs}.new" "${initramfs}"
-		set_sha1
+		# Guard against an unclean shutdown
+		sync -f "${initramfs}"
 	else
 		mkinitramfs_return="$?"
 		remove_initramfs_bak
 		rm -f "${initramfs}.new"
-		if [ "$mkinitramfs_return" = "2" ]; then
-			# minversion wasn't met, exit 0
-			exit 0
-		fi
-		echo "update-initramfs: failed for ${initramfs}" >&2
+		echo "update-initramfs: failed for ${initramfs} with $mkinitramfs_return." >&2
 		exit $mkinitramfs_return
 	fi
-}
-
-# lilo call
-run_lilo()
-{
-	# show lilo errors on failure
-	if ! lilo -t  > /dev/null 2>&1 ; then
-		echo "ERROR lilo fails for new ${initramfs}:" >&2
-		echo
-		lilo -t
-	fi
-	lilo
 }
 
 # Invoke bootloader
@@ -192,117 +157,46 @@ run_bootloader()
 {
 	# invoke policy conformant bootloader hooks
 	if [ -d /etc/initramfs/post-update.d/ ]; then
-		run-parts --arg=${version} --arg=${initramfs} \
+		run-parts --arg="${version}" --arg="${initramfs}" \
 			/etc/initramfs/post-update.d/
 		return 0
 	fi
-
-	# FIXME: to be removed postsqueeze release
-	# if both lilo and grub around, figure out if lilo needs to be run
-	if ( command -v update-grub >/dev/null 2>&1 \
-		|| [ -e /boot/grub/menu.lst ] || [ -e /boot/grub/grub.cfg ] ) \
-	&& ( [ -e /etc/lilo.conf ] && command -v lilo >/dev/null 2>&1 ); then
-		[ -r "${KPKGCONF}" ] && \
-		do_b=$(awk  '/^do_bootloader/{print $3}' "${KPKGCONF}")
-		if [ "${do_b}" = "yes" ] || [ "${do_b}" = "Yes" ] \
-		|| [ "${do_b}" = "YES" ]; then
-			run_lilo
-			return 0
-		elif [ "${do_b}" = "no" ] || [ "${do_b}" = "No" ] \
-		|| [ "${do_b}" = "NO" ]; then
-			return 0
-		fi
-
-		# do_bootloader unconfigured
-		echo
-		echo "WARNING: grub and lilo installed."
-		echo "Please deinstall unused bootloader."
-		echo
-		return 0
-	fi
-	if [ -r /etc/lilo.conf ] && command -v lilo >/dev/null 2>&1; then
-		run_lilo
-		return 0
-	fi
-	if [ -r /etc/elilo.conf ] && command -v elilo >/dev/null 2>&1; then
-		elilo
-		return 0
-	fi
-	if [ -r /etc/zipl.conf ]; then
-		zipl
-		return 0
-	fi
-	if flash-kernel --supported >/dev/null 2>&1; then
-		flash-kernel ${version}
-		return 0
-	fi
-}
-
-compare_sha1()
-{
-	sha1sum "${initramfs}" | diff "${STATEDIR}/${version}" - >/dev/null 2>&1
-	return $?
-}
-
-# Note that this must overwrite so that updates work.
-set_sha1()
-{
-	sha1sum "${initramfs}" > "${STATEDIR}/${version}"
-}
-
-delete_sha1()
-{
-	rm -f "${STATEDIR}/${version}"
 }
 
 # ro /boot is not modified
 ro_boot_check()
 {
 	# check irrelevant inside of a chroot
-	if [ ! -r /proc/mounts ] || chrooted; then
+	if [ ! -r /proc/mounts ] || ischroot; then
 		return 0
 	fi
 
+	# shellcheck disable=SC1004
 	boot_opts=$(awk '/boot/{if ((match($4, /^ro/) || match($4, /,ro/)) \
 		&& $2 == "/boot") print "ro"}' /proc/mounts)
 	if [ -n "${boot_opts}" ]; then
-		echo "WARNING: /boot is ro mounted."
-		echo "update-initramfs: Not updating ${initramfs}"
+		echo "W: /boot is ro mounted." >&2
+		echo "W: update-initramfs: Not updating ${initramfs}" >&2
 		exit 0
 	fi
 }
 
 get_sorted_versions()
 {
-	version_list=""
-
-	for gsv_x in "${STATEDIR}"/*; do
-		gsv_x="$(basename "${gsv_x}")"
-		if [ "${gsv_x}" = '*' ]; then
-			return 0
-		fi
-		worklist=""
-		for gsv_i in $version_list; do
-			if dpkg --compare-versions "${gsv_x}" '>' "${gsv_i}"; then
-				worklist="${worklist} ${gsv_x} ${gsv_i}"
-				gsv_x=""
-			else
-				worklist="${worklist} ${gsv_i}"
-			fi
-		done
-		if [ "${gsv_x}" != "" ]; then
-			worklist="${worklist} ${gsv_x}"
-		fi
-		version_list="${worklist}"
-	done
-
+	version_list="$(
+		linux-version list |
+		while read -r version; do
+		      test -e "${BOOTDIR}/initrd.img-$version" && echo "$version"
+		done |
+		linux-version sort --reverse
+		)"
 	verbose "Available versions: ${version_list}"
 }
 
 set_current_version()
 {
-	if [ -f /boot/initrd.img-`uname -r` ]; then
-		version=`uname -r`
+	if [ -f "/boot/initrd.img-$(uname -r)" ]; then
+		version=$(uname -r)
 	fi
 }
 
@@ -331,6 +225,7 @@ set_highest_version()
 		version=
 		return
 	fi
+	# shellcheck disable=SC2086
 	set -- ${version_list}
 	version=${1}
 }
@@ -338,22 +233,14 @@ set_highest_version()
 create()
 {
 	if [ -z "${version}" ]; then
-		usage "Create mode requires a version argument"
+		usage_error "Create mode requires a version argument"
 	fi
 
 	set_initramfs
 
-	if [ "${takeover}" = 0 ]; then
-		if version_exists "${version}"; then
-			panic "Cannot create version ${version}: already exists"
-		fi
-
-		if [ -e "${initramfs}" ]; then
-			panic "${initramfs} already exists, cannot create."
-		fi
-	fi
-
 	generate_initramfs
+
+	run_bootloader
 }
 
 update()
@@ -384,8 +271,6 @@ update()
 
 	ro_boot_check
 
-	altered_check
-
 	backup_initramfs
 
 	generate_initramfs
@@ -398,104 +283,90 @@ update()
 delete()
 {
 	if [ -z "${version}" ]; then
-		usage "Delete mode requires a version argument"
+		usage_error "Delete mode requires a version argument"
 	fi
 
 	set_initramfs
 
-	if [ "${takeover}" = 0 ]; then
-		if [ ! -e "${initramfs}" ]; then
-			panic "Cannot delete ${initramfs}, doesn't exist."
-		fi
-
-		if ! version_exists "${version}"; then
-			panic "Cannot delete version ${version}: Not created by this utility."
-		fi
-	fi
-
-	altered_check
-
 	echo "update-initramfs: Deleting ${initramfs}"
-
-	delete_sha1
 
 	rm -f "${initramfs}" "${initramfs}.bak"
 }
 
-# Check for update mode on existing and modified initramfs
-altered_check()
-{
-	# No check on takeover
-	[ "${takeover}" = 1 ] && return 0
-	if [ ! -e "${initramfs}" ]; then
-		mild_panic "${initramfs} does not exist. Cannot update."
-	fi
-	if ! compare_sha1; then
-		echo "update-initramfs: ${initramfs} has been altered." >&2
-		mild_panic "update-initramfs: Cannot update. Override with -t option."
-	fi
-}
-
 # Defaults
 verbose=0
-yes=0
-# We default to takeover=1 in Ubuntu, but not Debian
-takeover=0
 
 ##
 
-while getopts "k:cudyvtb:h?" flag; do
-	case "${flag}" in
-	k)
-		version="${OPTARG}"
+OPTIONS=$(getopt -o "k:cudvtb:h?" --long help -n "$0" -- "$@") || usage_error
+
+eval set -- "$OPTIONS"
+
+while true; do
+	case "$1" in
+	-k)
+		version="$2"
+		shift 2
 		;;
-	c)
+	-c)
 		mode="c"
+		shift
 		;;
-	d)
+	-d)
 		mode="d"
+		shift
 		;;
-	u)
+	-u)
 		mode="u"
+		shift
 		;;
-	v)
+	-v)
 		verbose="1"
+		shift
 		;;
-	y)
-		yes="1"
+	-t)
+		# accepted for compatibility, but ignored
+		shift
 		;;
-	t)
-		takeover="1"
-		;;
-	b)
-		BOOTDIR="${OPTARG}"
+	-b)
+		BOOTDIR="$2"
 		if [ ! -d "${BOOTDIR}" ]; then
-			echo "Error: ${BOOTDIR} is not a directory." >&2
+			echo "E: ${BOOTDIR} is not a directory." >&2
 			exit 1
 		fi
+		shift 2
 		;;
-	h|?)
+	-h|-\?|--help)
 		usage
+		exit 0
+		;;
+	--)
+		shift
+		break
 		;;
 	esac
 done
 
-shift $((${OPTIND} - 1))
-
 if [ $# -ne 0 ]; then
-	echo "Invalid argument for option -k." >&2
-	usage
+	printf "Extra argument '%s'\\n\\n" "$1" >&2
+	usage_error
 fi
 
 # Validate arguments
 if [ -z "${mode}" ]; then
-	usage "You must specify at least one of -c, -u, or -d."
+	usage_error "You must specify at least one of -c, -u, or -d."
 fi
 
 if [ "${version}" = "all" ] \
-	|| ( [ "${update_initramfs}" = "all" ] && [ -z "${version}" ] ); then
-	: FIXME check for --yes, and if not ask are you sure
-	get_sorted_versions
+	|| { [ "${update_initramfs}" = "all" ] && [ -z "${version}" ]; }; then
+	case "${mode}" in
+	c)
+		version_list="$(linux-version list)"
+		;;
+	d | u)
+		get_sorted_versions
+		;;
+	esac
 	if [ -z "${version_list}" ]; then
 		verbose "Nothing to do, exiting."
 		exit 0
@@ -505,14 +376,9 @@ if [ "${version}" = "all" ] \
 	if [ "${verbose}" = "1" ]; then
 		OPTS="${OPTS} -v"
 	fi
-	if [ "${takeover}" = "1" ]; then
-		OPTS="${OPTS} -t"
-	fi
-	if [ "${yes}" = "1" ]; then
-		OPTS="${OPTS} -y"
-	fi
 	for u_version in ${version_list}; do
 		verbose "Execute: ${0} -${mode} -k \"${u_version}\" ${OPTS}"
+		# shellcheck disable=SC2086
 		"${0}" -${mode} -k "${u_version}" ${OPTS}
 	done
 	exit 0
